model:
  type: DemoModel
  preprocessor:
    type: Preprocessor
    mean: [123.675, 116.28, 103.53]
    std: [58.395, 57.12, 57.375]
    bgr_to_rgb: True
    pad_size_divisor: 32

train_dataset:
  type: CocoDataset
  batch_size: 2
  num_works: 2
  data_root: /data/coco
  datasetwise_cfg:
    ann_file: annotations/instances_train2017.json
    img_path: train2017
  filter_cfg:
    filter_empty_gt: True
    min_size: 32
  batch_sampler:
    type: AspectRatioBatchSampler
  transforms:
    - type: LoadImageFromFile
    - type: LoadAnnotations
      with_bbox: True
    - type: Resize
      scale: (1333, 640)
      keep_ratio: True
    - type: RandomFlip
      prob: 0.5
    - type: PackDetInputs


optimizer:
  type: 'SGD'
  lr: 0.01

scheduler:
  - type: 'WarmUpLR'
    warmup_iters: 200
    warmup_ratio: 0.5
  - type: 'MultiStepLR'
    milestones: [3, 4]
    gamma: 0.1

train_loop:
  type: 'EpochTrainLoop'
  max_epoch: 10

hooks:
  - type: LoggerHook
    interval: 50

seed: 0
